### ISSUE TITLE
IntelliJ als Alternative

### ISSUE THREAD

**Issue by jan-christiansen** [HS-Flensburg-Algo/tutorials#5]
Neben dem Reiter, der die Verwendung von Eclipse erläutert, soll es einen Reiter geben, der erläutert, wie man die Aufgaben mit IntelliJ bearbeitet. Bitte auch einmal stichprobenartig testen, ob IntelliJ bei der Bearbeitung der Aufgaben Vorschläge macht, die in die falsche Richtung führen oder die Bearbeitung elementar vereinfacht.

**Comment by maximilian-steinberg** [comment]
Ich habe das Tutorial in einen eigenen Branch gepushed. Bei der Erstellung habe ich mich an den Punkten orientiert, welche für Eclipse bereitstehen und diese um Besonderheiten von IntelliJ ergänzt (z.B. Git Integration). 

Insgesamt habe ich etwas weniger Screenshots verwendet als beispielsweise bei Eclipse. 

Sollten hier noch Punkte überarbeitet, ergänzt oder entfernt werden? 

IntelliJ habe ich bei der Bearbeitung mehrerer Aufgaben getestet und konnte hier keine wesentlichen Unterschiede gegenüber Eclipse feststellen, welche das Lösen der Laboraufgaben erleichtert oder erschwert hätten.

**Comment by jan-christiansen** [comment]
Kannst du einen Pull-Request erstellen? Dann würde ich dort einmal Feedback schreiben.
